using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using Emberport.Models;

namespace Emberport.Services;

/// <summary>Prepares my.ini and creates the data directory on first use.</summary>
public static class MySqlConfigurator
{
    public const int DefaultPort = 3306;

    /// <summary>Kept outside the binaries folder so data survives a version switch.</summary>
    public static string DataDirectory => Path.Combine(AppPaths.DataRoot, "mysql");

    public static string ConfigFilePath => Path.Combine(AppPaths.ConfigRoot, "mysql", "my.ini");

    public static string EnsureConfigured(BinaryInstallation mysql, int port)
    {
        var configPath = ConfigFilePath;
        Directory.CreateDirectory(Path.GetDirectoryName(configPath)!);

        var builder = new StringBuilder();

        builder.AppendLine("# Generated by Emberport.");
        builder.AppendLine();
        builder.AppendLine("[mysqld]");
        builder.AppendLine($"basedir=\"{ToIniPath(mysql.DirectoryPath)}\"");
        builder.AppendLine($"datadir=\"{ToIniPath(DataDirectory)}\"");
        builder.AppendLine($"port={port}");
        builder.AppendLine("character-set-server=utf8mb4");
        builder.AppendLine("collation-server=utf8mb4_general_ci");
        builder.AppendLine("skip-name-resolve");
        builder.AppendLine("max_allowed_packet=128M");
        builder.AppendLine();
        builder.AppendLine("[client]");
        builder.AppendLine($"port={port}");
        builder.AppendLine("default-character-set=utf8mb4");

        File.WriteAllText(configPath, builder.ToString());

        return configPath;
    }

    public static bool IsInitialized() =>
        Directory.Exists(DataDirectory)
        && Directory.EnumerateFileSystemEntries(DataDirectory).Any();

    /// <summary>Runs mysqld --initialize-insecure once, creating a passwordless root user.</summary>
    public static void EnsureInitialized(BinaryInstallation mysql, string configPath)
    {
        if (IsInitialized())
        {
            return;
        }

        Directory.CreateDirectory(DataDirectory);

        var startInfo = new ProcessStartInfo
        {
            FileName = mysql.ExecutablePath,
            WorkingDirectory = mysql.DirectoryPath,
            UseShellExecute = false,
            CreateNoWindow = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
        };

        startInfo.ArgumentList.Add($"--defaults-file={configPath}");
        startInfo.ArgumentList.Add("--initialize-insecure");
        startInfo.ArgumentList.Add("--console");

        using var process = Process.Start(startInfo)
            ?? throw new InvalidOperationException("Could not launch mysqld.");

        var error = process.StandardError.ReadToEnd();
        process.WaitForExit();

        if (process.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"MySQL initialisation failed with exit code {process.ExitCode}.\n\n{error}");
        }
    }

    // MySQL treats a backslash inside my.ini as an escape character.
    private static string ToIniPath(string path) =>
        path.Replace('\\', '/').TrimEnd('/');
}