using System;
using System.IO;
using System.Security.Cryptography;
using System.Text.RegularExpressions;

namespace Emberport.Services;

/// <summary>Keeps tools\phpmyadmin\config.inc.php in sync with the MySQL settings.</summary>
public static partial class PhpMyAdminConfigurator
{
    public static string InstallDirectory => Path.Combine(AppPaths.ToolsRoot, "phpmyadmin");

    public static string ConfigFilePath => Path.Combine(InstallDirectory, "config.inc.php");

    /// <summary>Writes the configuration, reusing the existing secret. Returns null when phpMyAdmin is missing.</summary>
    public static string? EnsureConfigured(int port)
    {
        if (!Directory.Exists(InstallDirectory))
        {
            return null;
        }

        var tempDirectory = Path.Combine(AppPaths.DataRoot, "phpmyadmin", "tmp");
        Directory.CreateDirectory(tempDirectory);

        // Keeping the old secret means existing cookie sessions stay valid.
        var secret = ReadExistingSecret() ?? CreateSecret();
        var contents = Render(port, secret, ToPhpPath(tempDirectory));

        // Rewriting on every start would touch the file for no reason.
        if (!File.Exists(ConfigFilePath) || !string.Equals(File.ReadAllText(ConfigFilePath), contents, StringComparison.Ordinal))
        {
            File.WriteAllText(ConfigFilePath, contents);
        }

        return ConfigFilePath;
    }

    private static string Render(int port, string secret, string tempDirectory) =>
        $$"""
        <?php
        // Generated by Emberport. Manual changes are overwritten on the next start.
        declare(strict_types=1);

        $cfg['blowfish_secret'] = '{{secret}}';

        $i = 0;
        $i++;

        $cfg['Servers'][$i]['auth_type'] = 'cookie';
        $cfg['Servers'][$i]['host'] = '127.0.0.1';
        $cfg['Servers'][$i]['port'] = '{{port}}';
        $cfg['Servers'][$i]['compress'] = false;
        $cfg['Servers'][$i]['AllowNoPassword'] = true;
        $cfg['Servers'][$i]['AllowRoot'] = true;

        $cfg['TempDir'] = '{{tempDirectory}}';
        $cfg['SendErrorReports'] = 'never';
        $cfg['CheckConfigurationPermissions'] = false;
        $cfg['ShowPhpInfo'] = true;

        """;

    private static string? ReadExistingSecret()
    {
        if (!File.Exists(ConfigFilePath))
        {
            return null;
        }

        try
        {
            var match = SecretPattern().Match(File.ReadAllText(ConfigFilePath));

            return match.Success ? match.Groups[1].Value : null;
        }
        catch (IOException)
        {
            return null;
        }
    }

    private static string CreateSecret() =>
        Convert.ToHexString(RandomNumberGenerator.GetBytes(16)).ToLowerInvariant();

    // PHP is happier with forward slashes inside quoted paths on Windows.
    private static string ToPhpPath(string path) => path.Replace('\\', '/');

    [GeneratedRegex(@"blowfish_secret'\]\s*=\s*'([^']+)'")]
    private static partial Regex SecretPattern();
}