using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace Emberport.Services;

/// <summary>Writes config.inc.php so phpMyAdmin can reach the managed MySQL server.</summary>
public static class PhpMyAdminConfigurator
{
    public static string RootDirectory => Path.Combine(AppPaths.ToolsRoot, "phpmyadmin");

    public static string ConfigFilePath => Path.Combine(RootDirectory, "config.inc.php");

    public static bool IsInstalled() =>
        File.Exists(Path.Combine(RootDirectory, "index.php"));

    public static void EnsureConfigured(int mySqlPort)
    {
        if (!IsInstalled() || File.Exists(ConfigFilePath))
        {
            return;
        }

        var tempDirectory = Path.Combine(AppPaths.DataRoot, "phpmyadmin", "tmp");
        Directory.CreateDirectory(tempDirectory);

        File.WriteAllText(
            ConfigFilePath,
            BuildConfiguration(mySqlPort, ToPhpPath(tempDirectory)),
            new UTF8Encoding(false));
    }

    private static string BuildConfiguration(int mySqlPort, string tempDirectory)
    {
        var builder = new StringBuilder();

        builder.AppendLine("<?php");
        builder.AppendLine();
        builder.AppendLine("// Generated by Emberport. Delete this file to regenerate it.");
        builder.AppendLine();
        builder.AppendLine($"$cfg['blowfish_secret'] = '{CreateSecret()}';");
        builder.AppendLine();
        builder.AppendLine("$i = 0;");
        builder.AppendLine("$i++;");
        builder.AppendLine();
        builder.AppendLine("$cfg['Servers'][$i]['auth_type'] = 'cookie';");
        builder.AppendLine("$cfg['Servers'][$i]['host'] = '127.0.0.1';");
        builder.AppendLine($"$cfg['Servers'][$i]['port'] = '{mySqlPort}';");
        builder.AppendLine("$cfg['Servers'][$i]['compress'] = false;");
        builder.AppendLine("$cfg['Servers'][$i]['AllowNoPassword'] = true;");
        builder.AppendLine("$cfg['Servers'][$i]['AllowRoot'] = true;");
        builder.AppendLine();
        builder.AppendLine($"$cfg['TempDir'] = '{tempDirectory}';");
        builder.AppendLine("$cfg['UploadDir'] = '';");
        builder.AppendLine("$cfg['SaveDir'] = '';");
        builder.AppendLine("$cfg['SendErrorReports'] = 'never';");
        builder.AppendLine("$cfg['CheckConfigurationPermissions'] = false;");
        builder.AppendLine("$cfg['ShowPhpInfo'] = true;");

        return builder.ToString();
    }

    // A unique 32 character key per installation, never a hardcoded one.
    private static string CreateSecret() =>
        Convert.ToHexString(RandomNumberGenerator.GetBytes(16));

    private static string ToPhpPath(string path) =>
        path.Replace('\\', '/');
}